### ISSUE TITLE
Bruk av px og em i css

### ISSUE THREAD

**Issue by mikaelinmeta** [miljodir/md-components#106]
Vi i Tilde-prosjektet har til hensikt å gjenbruke CSS-pakken som er tilgjengelig i dette repoet for å holde enhetligheten så mye som mulig med designsystemet.

Men når vi ser på CSS-en, har vi kommet over 2 ting. Bruken av _px_ og _em_. Vi vil foreslå å erstatte begge disse med _rem_. Px til rem for responsivitet og accessibility. Er bruken av "em" et bevisst valg? Jeg er ikke så kjent med det, og det føles litt DX-uvennlig at du må holde styr på parents font-size.

Vi har ingen problemer med å opprette en pull request med disse endringene hvis ønskelig. Og hvis dere er enig, selvfølgelig 🙂

**Comment by kajsaeggum** [comment]
Veldig ønsket fra Grunnforurensnings-prosjektet også!

**Comment by aurorascharff** [comment]
@mikaelinmeta Det virket som alle er enige, har dere noen planer om å gjøre det?

**Comment by mikaelinmeta** [comment]
@aurorascharff Vi er ikke helt i tråd med CSS-en siden vårt design ble utformet før designsystemet ble opprettet, så vi har noe overstyrende CSS og ligger muligens et par versjoner bak (vanskelig å si når React og CSS-pakkingen er i samme repo).

Men jeg antar at Ingrid/noen ansvarlig kan ta en avgjørelse på hvem og når ressurser trengs for denne endringen, ikke sant?

Btw, her er en nice extension i VSCode for [px -> rem](https://marketplace.visualstudio.com/items?itemName=sainoba.px-to-rem)

**Comment by IngSchei** [comment]
@ohp-inmeta har du mulighet til å se på denne?

**Comment by ohp-inmeta** [comment]
> @ohp-inmeta har du mulighet til å se på denne?

Ikke på en stund, desverre..

**Comment by ohp-inmeta** [comment]
PR for dette klar: #187

**Comment by ohp-inmeta** [comment]
Da er dette inkludert i [md-css](https://www.npmjs.com/package/@miljodirektoratet/md-css) versjon 3.8.0
