### ISSUE TITLE
Oppdater inline link ut fra Figma-skisser

### ISSUE THREAD

**Issue by IngSchei** [miljodir/md-components#198]
Det er lagt til Figma-skisser på inline link (<a )
Juster kode slik at de stemmer overens

https://www.figma.com/design/6BUqOC0xQZz6AggPvI2iSR/Komponenter?m=auto&node-id=6010-9720&t=5uUNwhU5uKPX5NqC-1

**Comment by ohp-inmeta** [comment]
#201

**Comment by ohp-inmeta** [comment]
Ny lenke med icon finnes nå i pakkene og i storybook
