### ISSUE TITLE
Storybook bygger ikke på node 18

### ISSUE THREAD

**Issue by vstenvik** [miljodir/md-components#20]
Ved forsøk på å starte storybook på node 18 får jeg følgende feilmelding, mens på node 16 går det fint:

`Error: error:0308010C:digital envelope routines::unsupported`

Ser ut som at dette skyldes at storybook benytter en utdatert versjon av webpack

**Comment by aurorawalberg** [comment]
For å benytte nyere versjon av webpack ser det ut som man må migrere til storybook 7.  Kan det stemme?

**https://storybook.js.org/blog/storybook-for-webpack-5/**
**https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#start-storybook--build-storybook-binaries-removed**

**Comment by aurorawalberg** [comment]
Den nye javascript budler/runtime/test runner "Bun" kjører storybook helt supert i Windows Subsystem for Linux!!!! @vstenvik Hvis du har mac kan du bruke den i terminalem som vanlig, men ikke windows ennå.

**Comment by aurorawalberg** [comment]
Oppgradert storybook.
