### ISSUE TITLE
Critital security vulnerabilities

### ISSUE THREAD

**Issue by aurorascharff** [miljodir/md-components#203]
Er disse noe vi kan fikse?

❯ npm audit --fix
# npm audit report

parse-url  <=8.0.0
Severity: critical
parse-url parses http URLs incorrectly, making it vulnerable to host name spoofing - https://github.com/advisories/GHSA-pqw5-jmp5-px4v
Server-Side Request Forgery (SSRF) in GitHub repository ionicabizau/parse-url - https://github.com/advisories/GHSA-j9fq-vwqv-2fm2
No fix available
node_modules/parse-url
  git-up  <=6.0.0
  Depends on vulnerable versions of parse-url
  node_modules/git-up
    git-url-parse  4.0.0 - 12.0.0
    Depends on vulnerable versions of git-up
    node_modules/git-url-parse
      @storybook/storybook-deployer  *
      Depends on vulnerable versions of git-url-parse
      node_modules/@storybook/storybook-deployer

4 critical severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by ohp-inmeta** [comment]
Tested this, and storybook-deployer is no longer maintained. We use this to deploy to gh-pages, and it's this package that relies on parse-url.
